name: NIH STRIDES Visual Identity

repo:
- name: NIH STRIDES Visual Identity
  description: Main repository for the NIH STRIDES initiative's visual identity resources
  url: https://github.com/wangannie/brand

exclude:
- README.md
- LICENSE.md
- vendor

sass:
  style: nested
