name: NIH STRIDES Visual Identity

repo:
- name: NIH STRIDES Visual Identity
  description: Main repository for the NIH STRIDES Initiative's visual identity resources
  url: https://github.com/NIHGOV/STRIDES-Brand

exclude:
- README.md
- LICENSE.md
- vendor

sass:
  style: nested
